<?php
if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bAudited'])){
	if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bAudited']<>NULL){$FinancAudited=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bAudited'];}else{$FinancAudited=NULL;}	
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentAssets']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentAssets']['cCurrency']<>NULL){$FinancCurrentAssetCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentAssets']['cCurrency'];}else{$FinancCurrentAssetCur=NULL;}		
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentAssets']['cValue']<>NULL){$FinancCurrentAssetVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentAssets']['cValue'];}else{$FinancCurrentAssetVal=NULL;}
	}else{
		$FinancCurrentAssetVal=NULL;
		$FinancCurrentAssetCur=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bEquity']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bEquity']['cCurrency']<>NULL){$FinancEquityCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bEquity']['cCurrency'];}else{$FinancEquityCur=NULL;}		
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bEquity']['cValue']<>NULL){$FinancEquityVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bEquity']['cValue'];}else{$FinancEquityVal=NULL;}
	}else{
		$FinancEquityCur=NULL;
		$FinancEquityVal=NULL;
	}	
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentLiabilities']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentLiabilities']['cCurrency']<>NULL){$FinancCurrentLiabilitiesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentLiabilities']['cCurrency'];}else{$FinancCurrentLiabilitiesCur=NULL;}		
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentLiabilities']['cValue']<>NULL){$FinancCurrentLiabilitiesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bCurrentLiabilities']['cValue'];}else{$FinancCurrentLiabilitiesVal=NULL;}
	}else{
		$FinancCurrentLiabilitiesCur=NULL;
		$FinancCurrentLiabilitiesVal=NULL;
	}
	if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bForeignLoans']<>NULL){$FinancForeignLoans=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bForeignLoans'];}else{$FinancForeignLoans=NULL;}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bLiabilitiesToBank']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bLiabilitiesToBank']['cCurrency']<>NULL){$FinancLiabilitiesToBankCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bLiabilitiesToBank']['cCurrency'];}else{$FinancLiabilitiesToBankCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bLiabilitiesToBank']['cValue']<>NULL){$FinancLiabilitiesToBankVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bLiabilitiesToBank']['cValue'];}else{$FinancLiabilitiesToBankVal=NULL;}
	}else{
		$FinancLiabilitiesToBankCur=NULL;
		$FinancLiabilitiesToBankVal=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalExpenses']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalExpenses']['cCurrency']<>NULL){$FinancNonOprationalExpensesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalExpenses']['cCurrency'];}else{$FinancNonOprationalExpensesCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalExpenses']['cValue']<>NULL){$FinancNonOprationalExpensesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalExpenses']['cValue'];}else{$FinancNonOprationalExpensesVal=NULL;}
	}else{
		$FinancNonOprationalExpensesCur=NULL;
		$FinancNonOprationalExpensesVal=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalRevenues']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalRevenues']['cCurrency']<>NULL){$FinancNonOprationalRevenuesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalRevenues']['cCurrency'];}else{$FinancNonOprationalRevenuesCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalRevenues']['cValue']<>NULL){$FinancNonOprationalRevenuesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bNonOperationalRevenues']['cValue'];}else{$FinancNonOprationalRevenuesVal=NULL;}
	}else{
		$FinancNonOprationalRevenuesCur=NULL;
		$FinancNonOprationalRevenuesVal=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalExpenses']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalExpenses']['cCurrency']<>NULL){$FinancOprationalExpensesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalExpenses']['cCurrency'];}else{$FinancOprationalExpensesCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalExpenses']['cValue']<>NULL){$FinancOprationalExpensesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalExpenses']['cValue'];}else{$FinancOprationalExpensesVal=NULL;}
	}else{
		$FinancOprationalExpensesVal=NULL;
		$FinancOprationalExpensesCur=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalRevenues']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalRevenues']['cCurrency']<>NULL){$FinancOprationalRevenuesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalRevenues']['cCurrency'];}else{$FinancOprationalRevenuesCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalRevenues']['cValue']<>NULL){$FinancOprationalRevenuesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bOperationalRevenues']['cValue'];}else{$FinancOprationalRevenuesVal=NULL;}
	}else{
		$FinancOprationalRevenuesCur=NULL;
		$FinancOprationalRevenuesVal=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossCurrentYear']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossCurrentYear']['cCurrency']<>NULL){$FinancProfitLossCurrentYearCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossCurrentYear']['cCurrency'];}else{$FinancProfitLossCurrentYearCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossCurrentYear']['cValue']<>NULL){$FinancProfitLossCurrentYearVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossCurrentYear']['cValue'];}else{$FinancProfitLossCurrentYearVal=NULL;}
	}else{
		$FinancProfitLossCurrentYearCur=NULL;
		$FinancProfitLossCurrentYearVal=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossPreviousYear']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossPreviousYear']['cCurrency']<>NULL){$FinancProfitLossPreviousYearCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossPreviousYear']['cCurrency'];}else{$FinancProfitLossPreviousYearCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossPreviousYear']['cValue']<>NULL){$FinancProfitLossPreviousYearVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bProfitLossPreviousYear']['cValue'];}else{$FinancProfitLossPreviousYearVal=NULL;}
	}else{
		$FinancProfitLossPreviousYearCur=NULL;
		$FinancProfitLossPreviousYearVal=NULL;
	}
	if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bReportedDate']<>NULL){$FinancReportDate=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bReportedDate'];}else{$FinancReportDate=NULL;}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSales']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSales']['cCurrency']<>NULL){$FinancSalesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSales']['cCurrency'];}else{$FinancSalesCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSales']['cValue']<>NULL){$FinancSalesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSales']['cValue'];}else{$FinancSalesVal=NULL;}
	}else{
		$FinancSalesVal=NULL;
		$FinancSalesCur=NULL;
	}
	if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSubscriber']<>NULL){$FinancSubscriber=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bSubscriber'];}else{$FinancSubscriber=NULL;}	
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalAssets']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalAssets']['cCurrency']<>NULL){$FinancTotalAssetCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalAssets']['cCurrency'];}else{$FinancTotalAssetCur=NULL;}
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalAssets']['cValue']<>NULL){$FinancTotalAssetVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalAssets']['cValue'];}else{$FinancTotalAssetVal=NULL;}
	}else{
		$FinancTotalAssetCur=NULL;
		$FinancTotalAssetVal=NULL;
	}
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalLiabilities']['cCurrency'])){
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalLiabilities']['cCurrency']<>NULL){$FinancTotalLiabilitiesCur=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalLiabilities']['cCurrency'];}else{$FinancTotalLiabilitiesCur=NULL;}		
		if($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalLiabilities']['cValue']<>NULL){$FinancTotalLiabilitiesVal=$array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement']['bTotalLiabilities']['cValue'];}else{$FinancTotalLiabilitiesVal=NULL;}
	}else{
		$FinancTotalLiabilitiesVal=NULL;
		$FinancTotalLiabilitiesCur=NULL;
	}

	$callFinancial = "{call SP_INSERT_M_FINANCIAL_COMPANY(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
	$paramsFinancial = array(
						array($mappingId, SQLSRV_PARAM_IN),
						array($pefindoId,SQLSRV_PARAM_IN),
						array(NULL,SQLSRV_PARAM_IN),
						array($FinancAudited,SQLSRV_PARAM_IN),
						array($FinancCurrentAssetCur,SQLSRV_PARAM_IN),
						array($FinancCurrentAssetVal,SQLSRV_PARAM_IN),
						array($FinancCurrentLiabilitiesCur,SQLSRV_PARAM_IN),
						array($FinancCurrentLiabilitiesVal,SQLSRV_PARAM_IN),
						array($FinancEquityCur,SQLSRV_PARAM_IN),
						array($FinancEquityVal,SQLSRV_PARAM_IN),
						array($FinancForeignLoans,SQLSRV_PARAM_IN),
						array($FinancLiabilitiesToBankCur,SQLSRV_PARAM_IN),
						array($FinancLiabilitiesToBankVal,SQLSRV_PARAM_IN),
						array($FinancNonOprationalExpensesCur,SQLSRV_PARAM_IN),
						array($FinancNonOprationalExpensesVal,SQLSRV_PARAM_IN),
						array($FinancNonOprationalRevenuesCur,SQLSRV_PARAM_IN),
						array($FinancNonOprationalRevenuesVal,SQLSRV_PARAM_IN),
						array($FinancOprationalExpensesCur,SQLSRV_PARAM_IN),
						array($FinancOprationalExpensesVal,SQLSRV_PARAM_IN),
						array($FinancOprationalRevenuesCur,SQLSRV_PARAM_IN),
						array($FinancOprationalRevenuesVal,SQLSRV_PARAM_IN),
						array($FinancProfitLossCurrentYearCur,SQLSRV_PARAM_IN),
						array($FinancProfitLossCurrentYearVal,SQLSRV_PARAM_IN),
						array($FinancProfitLossPreviousYearCur,SQLSRV_PARAM_IN),
						array($FinancProfitLossPreviousYearVal,SQLSRV_PARAM_IN),
						array($FinancReportDate,SQLSRV_PARAM_IN),
						array($FinancSalesCur,SQLSRV_PARAM_IN),
						array($FinancSalesVal,SQLSRV_PARAM_IN),
						array($FinancSubscriber,SQLSRV_PARAM_IN),
						array($FinancTotalAssetCur,SQLSRV_PARAM_IN),
						array($FinancTotalAssetVal,SQLSRV_PARAM_IN),
						array($FinancTotalLiabilitiesCur,SQLSRV_PARAM_IN),
						array($FinancTotalLiabilitiesVal,SQLSRV_PARAM_IN)
						);
	$execFinancial = sqlsrv_query($conn, $callFinancial, $paramsFinancial) or die ( print_r( sqlsrv_errors(),true));
}else{
	if(isset($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement'])){
		foreach($array['GetCustomReportResponse']['GetCustomReportResult']['aFinancials']['bFinancialStatementList']['bFinancialStatement'] as $itemFinancial){
			if($itemFinancial['bAudited']<>NULL){$FinancAudited=$itemFinancial['bAudited'];}else{$FinancAudited=NULL;}	
			if(isset($itemFinancial['bCurrentAssets']['cCurrency'])){
				if($itemFinancial['bCurrentAssets']['cCurrency']<>NULL){$FinancCurrentAssetCur=$itemFinancial['bCurrentAssets']['cCurrency'];}else{$FinancCurrentAssetCur=NULL;}			
				if($itemFinancial['bCurrentAssets']['cValue']<>NULL){$FinancCurrentAssetVal=$itemFinancial['bCurrentAssets']['cValue'];}else{$FinancCurrentAssetVal=NULL;}
			}else{
				$FinancCurrentAssetVal=NULL;
				$FinancCurrentAssetCur=NULL;
			}
			if(isset($itemFinancial['bEquity']['cCurrency'])){
				if($itemFinancial['bEquity']['cCurrency']<>NULL){$FinancEquityCur=$itemFinancial['bEquity']['cCurrency'];}else{$FinancEquityCur=NULL;}			
				if($itemFinancial['bEquity']['cValue']<>NULL){$FinancEquityVal=$itemFinancial['bEquity']['cValue'];}else{$FinancEquityVal=NULL;}
			}else{
				$FinancEquityCur=NULL;
				$FinancEquityVal=NULL;
			}		
			if(isset($itemFinancial['bCurrentLiabilities']['cCurrency'])){
				if($itemFinancial['bCurrentLiabilities']['cCurrency']<>NULL){$FinancCurrentLiabilitiesCur=$itemFinancial['bCurrentLiabilities']['cCurrency'];}else{$FinancCurrentLiabilitiesCur=NULL;}			
				if($itemFinancial['bCurrentLiabilities']['cValue']<>NULL){$FinancCurrentLiabilitiesVal=$itemFinancial['bCurrentLiabilities']['cValue'];}else{$FinancCurrentLiabilitiesVal=NULL;}
			}else{
				$FinancCurrentLiabilitiesCur=NULL;
				$FinancCurrentLiabilitiesVal=NULL;
			}
			if($itemFinancial['bForeignLoans']<>NULL){$FinancForeignLoans=$itemFinancial['bForeignLoans'];}else{$FinancForeignLoans=NULL;}
			if(isset($itemFinancial['bLiabilitiesToBank']['cCurrency'])){
				if($itemFinancial['bLiabilitiesToBank']['cCurrency']<>NULL){$FinancLiabilitiesToBankCur=$itemFinancial['bLiabilitiesToBank']['cCurrency'];}else{$FinancLiabilitiesToBankCur=NULL;}			
				if($itemFinancial['bLiabilitiesToBank']['cValue']<>NULL){$FinancLiabilitiesToBankVal=$itemFinancial['bLiabilitiesToBank']['cValue'];}else{$FinancLiabilitiesToBankVal=NULL;}
			}else{
				$FinancLiabilitiesToBankCur=NULL;
				$FinancLiabilitiesToBankVal=NULL;
			}
			if(isset($itemFinancial['bNonOperationalExpenses']['cCurrency'])){
				if($itemFinancial['bNonOperationalExpenses']['cCurrency']<>NULL){$FinancNonOprationalExpensesCur=$itemFinancial['bNonOperationalExpenses']['cCurrency'];}else{$FinancNonOprationalExpensesCur=NULL;}			
				if($itemFinancial['bNonOperationalExpenses']['cValue']<>NULL){$FinancNonOprationalExpensesVal=$itemFinancial['bNonOperationalExpenses']['cValue'];}else{$FinancNonOprationalExpensesVal=NULL;}
			}else{
				$FinancNonOprationalExpensesCur=NULL;
				$FinancNonOprationalExpensesVal=NULL;
			}
			if(isset($itemFinancial['bNonOperationalRevenues']['cCurrency'])){
				if($itemFinancial['bNonOperationalRevenues']['cCurrency']<>NULL){$FinancNonOprationalRevenuesCur=$itemFinancial['bNonOperationalRevenues']['cCurrency'];}else{$FinancNonOprationalRevenuesCur=NULL;}
				if($itemFinancial['bNonOperationalRevenues']['cValue']<>NULL){$FinancNonOprationalRevenuesVal=$itemFinancial['bNonOperationalRevenues']['cValue'];}else{$FinancNonOprationalRevenuesVal=NULL;}
			}else{
				$FinancNonOprationalRevenuesCur=NULL;
				$FinancNonOprationalRevenuesVal=NULL;
			}
			if(isset($itemFinancial['bOperationalExpenses']['cCurrency'])){
				if($itemFinancial['bOperationalExpenses']['cCurrency']<>NULL){$FinancOprationalExpensesCur=$itemFinancial['bOperationalExpenses']['cCurrency'];}else{$FinancOprationalExpensesCur=NULL;}	
				if($itemFinancial['bOperationalExpenses']['cValue']<>NULL){$FinancOprationalExpensesVal=$itemFinancial['bOperationalExpenses']['cValue'];}else{$FinancOprationalExpensesVal=NULL;}
			}else{
				$FinancOprationalExpensesVal=NULL;
				$FinancOprationalExpensesCur=NULL;
			}
			if(isset($itemFinancial['bOperationalRevenues']['cCurrency'])){
				if($itemFinancial['bOperationalRevenues']['cCurrency']<>NULL){$FinancOprationalRevenuesCur=$itemFinancial['bOperationalRevenues']['cCurrency'];}else{$FinancOprationalRevenuesCur=NULL;}			
				if($itemFinancial['bOperationalRevenues']['cValue']<>NULL){$FinancOprationalRevenuesVal=$itemFinancial['bOperationalRevenues']['cValue'];}else{$FinancOprationalRevenuesVal=NULL;}
			}else{
				$FinancOprationalRevenuesCur=NULL;
				$FinancOprationalRevenuesVal=NULL;
			}
			if(isset($itemFinancial['bProfitLossCurrentYear']['cCurrency'])){
				if($itemFinancial['bProfitLossCurrentYear']['cCurrency']<>NULL){$FinancProfitLossCurrentYearCur=$itemFinancial['bProfitLossCurrentYear']['cCurrency'];}else{$FinancProfitLossCurrentYearCur=NULL;}			
				if($itemFinancial['bProfitLossCurrentYear']['cValue']<>NULL){$FinancProfitLossCurrentYearVal=$itemFinancial['bProfitLossCurrentYear']['cValue'];}else{$FinancProfitLossCurrentYearVal=NULL;}
			}else{
				$FinancProfitLossCurrentYearCur=NULL;
				$FinancProfitLossCurrentYearVal=NULL;
			}
			if(isset($itemFinancial['bProfitLossPreviousYear']['cCurrency'])){
				if($itemFinancial['bProfitLossPreviousYear']['cCurrency']<>NULL){$FinancProfitLossPreviousYearCur=$itemFinancial['bProfitLossPreviousYear']['cCurrency'];}else{$FinancProfitLossPreviousYearCur=NULL;}			
				if($itemFinancial['bProfitLossPreviousYear']['cValue']<>NULL){$FinancProfitLossPreviousYearVal=$itemFinancial['bProfitLossPreviousYear']['cValue'];}else{$FinancProfitLossPreviousYearVal=NULL;}
			}else{
				$FinancProfitLossPreviousYearCur=NULL;
				$FinancProfitLossPreviousYearVal=NULL;
			}
			if($itemFinancial['bReportedDate']<>NULL){$FinancReportDate=$itemFinancial['bReportedDate'];}else{$FinancReportDate=NULL;}
			if(isset($itemFinancial['bSales']['cCurrency'])){
				if($itemFinancial['bSales']['cCurrency']<>NULL){$FinancSalesCur=$itemFinancial['bSales']['cCurrency'];}else{$FinancSalesCur=NULL;}
				if($itemFinancial['bSales']['cValue']<>NULL){$FinancSalesVal=$itemFinancial['bSales']['cValue'];}else{$FinancSalesVal=NULL;}
			}else{
				$FinancSalesVal=NULL;
				$FinancSalesCur=NULL;
			}
			if($itemFinancial['bSubscriber']<>NULL){$FinancSubscriber=$itemFinancial['bSubscriber'];}else{$FinancSubscriber=NULL;}
			if(isset($itemFinancial['bTotalAssets']['cCurrency'])){
				if($itemFinancial['bTotalAssets']['cCurrency']<>NULL){$FinancTotalAssetCur=$itemFinancial['bTotalAssets']['cCurrency'];}else{$FinancTotalAssetCur=NULL;}
				if($itemFinancial['bTotalAssets']['cValue']<>NULL){$FinancTotalAssetVal=$itemFinancial['bTotalAssets']['cValue'];}else{$FinancTotalAssetVal=NULL;}
			}else{
				$FinancTotalAssetCur=NULL;
				$FinancTotalAssetVal=NULL;
			}
			if(isset($itemFinancial['bTotalLiabilities']['cCurrency'])){
				if($itemFinancial['bTotalLiabilities']['cCurrency']<>NULL){$FinancTotalLiabilitiesCur=$itemFinancial['bTotalLiabilities']['cCurrency'];}else{$FinancTotalLiabilitiesCur=NULL;}	
				if($itemFinancial['bTotalLiabilities']['cValue']<>NULL){$FinancTotalLiabilitiesVal=$itemFinancial['bTotalLiabilities']['cValue'];}else{$FinancTotalLiabilitiesVal=NULL;}
			}else{
				$FinancTotalLiabilitiesVal=NULL;
				$FinancTotalLiabilitiesCur=NULL;
			}

			$callFinancial = "{call SP_INSERT_M_FINANCIAL_COMPANY(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
			$paramsFinancial = array(
								array($mappingId, SQLSRV_PARAM_IN),
								array($pefindoId,SQLSRV_PARAM_IN),
								array(NULL,SQLSRV_PARAM_IN),
								array($FinancAudited,SQLSRV_PARAM_IN),
								array($FinancCurrentAssetCur,SQLSRV_PARAM_IN),
								array($FinancCurrentAssetVal,SQLSRV_PARAM_IN),
								array($FinancCurrentLiabilitiesCur,SQLSRV_PARAM_IN),
								array($FinancCurrentLiabilitiesVal,SQLSRV_PARAM_IN),
								array($FinancEquityCur,SQLSRV_PARAM_IN),
								array($FinancEquityVal,SQLSRV_PARAM_IN),
								array($FinancForeignLoans,SQLSRV_PARAM_IN),
								array($FinancLiabilitiesToBankCur,SQLSRV_PARAM_IN),
								array($FinancLiabilitiesToBankVal,SQLSRV_PARAM_IN),
								array($FinancNonOprationalExpensesCur,SQLSRV_PARAM_IN),
								array($FinancNonOprationalExpensesVal,SQLSRV_PARAM_IN),
								array($FinancNonOprationalRevenuesCur,SQLSRV_PARAM_IN),
								array($FinancNonOprationalRevenuesVal,SQLSRV_PARAM_IN),
								array($FinancOprationalExpensesCur,SQLSRV_PARAM_IN),
								array($FinancOprationalExpensesVal,SQLSRV_PARAM_IN),
								array($FinancOprationalRevenuesCur,SQLSRV_PARAM_IN),
								array($FinancOprationalRevenuesVal,SQLSRV_PARAM_IN),
								array($FinancProfitLossCurrentYearCur,SQLSRV_PARAM_IN),
								array($FinancProfitLossCurrentYearVal,SQLSRV_PARAM_IN),
								array($FinancProfitLossPreviousYearCur,SQLSRV_PARAM_IN),
								array($FinancProfitLossPreviousYearVal,SQLSRV_PARAM_IN),
								array($FinancReportDate,SQLSRV_PARAM_IN),
								array($FinancSalesCur,SQLSRV_PARAM_IN),
								array($FinancSalesVal,SQLSRV_PARAM_IN),
								array($FinancSubscriber,SQLSRV_PARAM_IN),
								array($FinancTotalAssetCur,SQLSRV_PARAM_IN),
								array($FinancTotalAssetVal,SQLSRV_PARAM_IN),
								array($FinancTotalLiabilitiesCur,SQLSRV_PARAM_IN),
								array($FinancTotalLiabilitiesVal,SQLSRV_PARAM_IN)
								);
			$execFinancial = sqlsrv_query($conn, $callFinancial, $paramsFinancial) or die ( print_r( sqlsrv_errors(),true));
			
		}
	}
}
?>